### ISSUE TITLE
Morning 

### ISSUE THREAD

**Issue by maryamawancute** [subsquid-quests/triple-chain-squid#6]
https://github.com/subsquid-quests/triple-chain-squid/blob/master/docker-compose.yml

**Comment by maryamawancute** [comment]
https://github.com/subsquid-quests/triple-chain-squid/blob/master/docker-compose.yml

**Comment by maryamawancute** [comment]
No DC ja hmm u😯😨😯😨😨😵‍💫😯😵‍💫😯🫨😵‍💫😣😵‍💫😣🫨😩😵‍💫😩🫨

**Comment by AlfinLianto** [comment]
nices

**Comment by maryamawancute** [comment]
Nff yhccgguxxg
